import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import '@mantine/core/styles.css';

import { ColorSchemeScript, MantineProvider } from '@mantine/core';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
        <title>fml</title>
      </head>
      <body className={inter.className}>
        <MantineProvider>
            <div className={`bg-gray-100 flex min-w-screen min-h-screen items-center justify-center text-gray-800`}>
                {children}
            </div>
        </MantineProvider>
      </body>
    </html>
  );
}
